name: prod - Build and Push

env:
    # Azure ACR
    ACR_HOST: ${{ vars.REGISTRY_LOGIN_SERVER_PROD }}
    ACR_USER: ${{ secrets.REGISTRY_USERNAME_PROD }}
    ACR_PASS: ${{ secrets.REGISTRY_PASSWORD_PROD }}

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: log in to ACR
              uses: azure/docker-login@v1
              with:
                login-server: ${{ env.ACR_HOST }}
                username: ${{ env.ACR_USER }}
                password: ${{ env.ACR_PASS }}

            - name: build and push docker container
              run: |
                docker build -t ${{ env.ACR_HOST }}/paychex/rag_api:prod.${{ github.sha }} -f ./PaychexDockerfile .
                docker push ${{ env.ACR_HOST }}/paychex/rag_api:prod.${{ github.sha }}

                docker build -t ${{ env.ACR_HOST }}/paychex/rag_api:prod.latest -f ./PaychexDockerfile .
                docker push ${{ env.ACR_HOST }}/paychex/rag_api:prod.latest
